package br.metodista.ads.telas;

import br.metodista.ads.dao.LivroDao;
import br.metodista.ads.dao.UsuarioDao;
import br.metodista.ads.modelos.Emprestimo;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {
   
  /**
   * Creates new form Principal
   */
  public Principal() {
    initComponents();
    //Abrir a tela maximizada.
    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    this.getContentPane().setBackground(Color.white);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuUsuario = new javax.swing.JMenu();
        menuGerenciarUsuario = new javax.swing.JMenuItem();
        separador = new javax.swing.JPopupMenu.Separator();
        menuSair = new javax.swing.JMenuItem();
        menuLivro = new javax.swing.JMenu();
        menuGerenciarLivro = new javax.swing.JMenuItem();
        menuEmprestar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuListaEmprestimo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Livros");

        menuArquivo.setText("Arquivo");

        menuUsuario.setText("Usuário");

        menuGerenciarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        menuGerenciarUsuario.setText("Gerenciar");
        menuGerenciarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciarUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(menuGerenciarUsuario);

        menuArquivo.add(menuUsuario);
        menuArquivo.add(separador);

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuSair);

        menu.add(menuArquivo);

        menuLivro.setText("Livro");

        menuGerenciarLivro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        menuGerenciarLivro.setText("Gerenciar");
        menuGerenciarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciarLivroActionPerformed(evt);
            }
        });
        menuLivro.add(menuGerenciarLivro);

        menuEmprestar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        menuEmprestar.setText("Emprestar");
        menuEmprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmprestarActionPerformed(evt);
            }
        });
        menuLivro.add(menuEmprestar);

        menu.add(menuLivro);

        jMenu1.setText("Relatório");

        menuListaEmprestimo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        menuListaEmprestimo.setText("Lista de Emprestimos");
        menuListaEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListaEmprestimoActionPerformed(evt);
            }
        });
        jMenu1.add(menuListaEmprestimo);

        menu.add(jMenu1);

        setJMenuBar(menu);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 357, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
  private void abrirJanela(JFrame jFrame) {
    jFrame.setVisible(true);
    jFrame.setLocationRelativeTo(null);
  }
  
  private void menuGerenciarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciarLivroActionPerformed
    abrirJanela(new TelaLivro());
  }//GEN-LAST:event_menuGerenciarLivroActionPerformed

  private void menuGerenciarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciarUsuarioActionPerformed
    abrirJanela(new TelaUsuario());
    
  }//GEN-LAST:event_menuGerenciarUsuarioActionPerformed

  private void menuEmprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmprestarActionPerformed
    abrirJanela(new TelaEmprestimo());
  }//GEN-LAST:event_menuEmprestarActionPerformed

  private void menuListaEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListaEmprestimoActionPerformed
    abrirJanela(new RelatorioEmprestimo());
  }//GEN-LAST:event_menuListaEmprestimoActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        //Fecha a aplicação
      if (JOptionPane.showConfirmDialog(this, "Deseja realmente sair do sistema?", "Controle de Livros", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
          this.dispose();
          System.exit(0);
      }
    }//GEN-LAST:event_menuSairActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Principal().setVisible(true);
      }
    });
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuItem menuEmprestar;
    private javax.swing.JMenuItem menuGerenciarLivro;
    private javax.swing.JMenuItem menuGerenciarUsuario;
    private javax.swing.JMenuItem menuListaEmprestimo;
    private javax.swing.JMenu menuLivro;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JPopupMenu.Separator separador;
    // End of variables declaration//GEN-END:variables
}
