/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.metodista.ads.telas;

import br.metodista.ads.modelos.Livro;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sakurai
 */
public class TelaLivro extends javax.swing.JFrame {

  private List<Livro> livros = null;
  private int linhaSelecionada = -1;
  
  /**
   * Creates new form TelaLivro
   */
  public TelaLivro(List<Livro> livros) {
    this.livros = livros;
    initComponents();
    carregarLivros();
    this.remover.setEnabled(false);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    isbn = new javax.swing.JTextField();
    paginas = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    titulo = new javax.swing.JTextField();
    autor = new javax.swing.JTextField();
    edicao = new javax.swing.JTextField();
    novo = new javax.swing.JButton();
    salvar = new javax.swing.JButton();
    remover = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tabela = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Cadastro de Livro");

    jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Cadastro de Livro");

    jLabel2.setText("ISBN:");

    jLabel3.setText("Páginas:");

    jLabel4.setText("Edição:");

    jLabel5.setText("Título:");

    jLabel6.setText("Autor:");

    org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jPanel1Layout.createSequentialGroup()
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(jLabel2)
              .add(jLabel3)
              .add(jLabel4))
            .add(18, 18, 18)
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
              .add(paginas, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
              .add(isbn)
              .add(edicao))
            .add(0, 0, Short.MAX_VALUE))
          .add(jPanel1Layout.createSequentialGroup()
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(jLabel5)
              .add(jLabel6))
            .add(29, 29, 29)
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(autor)
              .add(titulo))))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel5)
          .add(titulo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(autor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(jLabel6))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel2)
          .add(isbn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel3)
          .add(paginas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel4)
          .add(edicao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
    );

    novo.setText("Novo");
    novo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        novoActionPerformed(evt);
      }
    });

    salvar.setText("Salvar");
    salvar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        salvarActionPerformed(evt);
      }
    });

    remover.setText("Remover");
    remover.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        removerActionPerformed(evt);
      }
    });

    tabela.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Título", "Autor", "ISBN", "Páginas", "Edição"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, true, true, true
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tabela.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tabelaMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tabela);

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
          .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
          .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
            .add(novo)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(salvar)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(remover)
            .add(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(jLabel1)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(novo)
          .add(salvar)
          .add(remover))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed
    limparDados();
  }//GEN-LAST:event_novoActionPerformed

  private void limparDados() {
    this.titulo.setText("");
    this.autor.setText("");
    this.isbn.setText("");
    this.paginas.setText("");
    this.edicao.setText("");
    
    this.linhaSelecionada = -1;
    this.titulo.setEnabled(true);
    this.remover.setEnabled(false);
  }
  
  private Livro obterLivro(List<Livro> livros, String titulo) {
    Livro livro = null;
    //Percorre todos os livros para verificar se existe um livro com o titulo informado.
    for(Livro u : livros) {
      if(u.getTitulo().equals(titulo)) {
        livro = u;
        //Se encontrar o livro, para de procurar.
        break;
      }
    }
    
    return livro;
  }
  
  private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
    Livro l = obterLivro(livros, titulo.getText());

    //Se o livro for novo adiciona ele na lista.
    if(l == null) {
      l = new Livro();
      l.setTitulo(titulo.getText());
      l.setAutor(autor.getText());
      l.setIsbn(isbn.getText());
      l.setPaginas(Integer.parseInt(paginas.getText()));
      l.setEdicao(Integer.parseInt(edicao.getText()));

      livros.add(l);
    } else {
      //Se o livro já existir apenas atualiza o autor, isbn, paginas, edicao.
      l.setAutor(autor.getText());
      l.setIsbn(isbn.getText());
      l.setPaginas(Integer.parseInt(paginas.getText()));
      l.setEdicao(Integer.parseInt(edicao.getText()));
    }

    carregarLivros();

    limparDados();
  }//GEN-LAST:event_salvarActionPerformed

  private void removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerActionPerformed
    //Remove o livro da lista.
    livros.remove(linhaSelecionada);

    //Remove o livro da tabela.
    ((DefaultTableModel) tabela.getModel()).removeRow(linhaSelecionada);

    limparDados();
  }//GEN-LAST:event_removerActionPerformed

  private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
    //Linha da tabela que foi clicada.
    linhaSelecionada = tabela.getSelectedRow();

    //Obtém o livro da linha selecionada e preenche o formulário.
    Livro u = livros.get(linhaSelecionada);
    preencherDadosLivro(u);

    //Arruma os controles.
    this.titulo.setEnabled(false);
    this.remover.setEnabled(true);
  }//GEN-LAST:event_tabelaMouseClicked

  private void preencherDadosLivro(Livro l) {
    this.titulo.setText(l.getTitulo());
    this.autor.setText(l.getAutor());
    this.isbn.setText(l.getIsbn());
    this.paginas.setText(String.valueOf(l.getPaginas()));
    this.edicao.setText(String.valueOf(l.getEdicao()));
  }
  
  private void carregarLivros() {
    //Remove todos os livros da tabela.
    for(int cont = tabela.getRowCount() - 1; cont >= 0; cont--) {
      ((DefaultTableModel) tabela.getModel()).removeRow(cont);
    }
    
    //Adiciona todos os livros na tabela.
    for(Livro l : livros) {
      ((DefaultTableModel) tabela.getModel()).addRow(l.carregarGrid());
    }
  }
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new TelaLivro(new ArrayList<Livro>()).setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField autor;
  private javax.swing.JTextField edicao;
  private javax.swing.JTextField isbn;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JButton novo;
  private javax.swing.JTextField paginas;
  private javax.swing.JButton remover;
  private javax.swing.JButton salvar;
  private javax.swing.JTable tabela;
  private javax.swing.JTextField titulo;
  // End of variables declaration//GEN-END:variables
}
