-- USER SQL
CREATE USER LIVROS IDENTIFIED BY 123456 ;

-- QUOTAS
ALTER USER LIVROS QUOTA UNLIMITED ON USERS;

-- ROLES

-- SYSTEM PRIVILEGES
GRANT ALTER SESSION TO "LIVROS" ;
GRANT CREATE SESSION TO "LIVROS" ;
GRANT DROP ANY TRIGGER TO LIVROS ;
GRANT ALTER ANY INDEX TO LIVROS ;
GRANT CREATE TRIGGER TO LIVROS ;
GRANT CREATE ANY INDEX TO LIVROS ;
GRANT CREATE INDEXTYPE TO LIVROS ;
GRANT CREATE VIEW TO LIVROS ;
GRANT ALTER ANY TABLE TO LIVROS ;
GRANT SELECT ANY TABLE TO LIVROS ;
GRANT DELETE ANY TABLE TO LIVROS ;
GRANT CREATE TABLE TO LIVROS ;
GRANT DROP ANY TABLE TO LIVROS ;
GRANT EXECUTE ANY PROCEDURE TO LIVROS ;
GRANT UPDATE ANY TABLE TO LIVROS ;
GRANT DROP ANY VIEW TO LIVROS ;
GRANT ALTER ANY TRIGGER TO LIVROS ;
GRANT CREATE ANY VIEW TO LIVROS ;
GRANT CREATE ANY TRIGGER TO LIVROS ;
GRANT CREATE ANY TABLE TO LIVROS ;
GRANT CREATE PROCEDURE TO LIVROS ;
GRANT DROP ANY SEQUENCE TO "LIVROS" ;
GRANT CREATE ANY SEQUENCE TO "LIVROS" ;
GRANT ALTER ANY SEQUENCE TO "LIVROS" ;
GRANT UNDER ANY TABLE TO "LIVROS" ;
GRANT CREATE ANY PROCEDURE TO "LIVROS" ;
GRANT DEBUG CONNECT SESSION TO "LIVROS" ;
GRANT DEBUG ANY PROCEDURE TO "LIVROS" ;
GRANT SELECT ANY SEQUENCE TO "LIVROS" ;
GRANT CREATE TYPE TO "LIVROS" ;
GRANT CREATE TABLESPACE TO "LIVROS" ;
GRANT DROP ANY TYPE TO "LIVROS" ;
GRANT CREATE SEQUENCE TO "LIVROS" ;
GRANT ALTER TABLESPACE TO "LIVROS" ;
GRANT UNDER ANY VIEW TO "LIVROS" ;
GRANT DROP ANY PROCEDURE TO "LIVROS" ;
GRANT UNLIMITED TABLESPACE TO "LIVROS" ;
GRANT DROP TABLESPACE TO "LIVROS" ;

CREATE SEQUENCE USUARIOS_LIVROS_SEQ INCREMENT BY 1 START WITH 1;

CREATE TABLE USUARIOS(
    ID      INT,
    NOME    VARCHAR2(100),
    LOGIN   VARCHAR2(50),
    SENHA   VARCHAR2(20)
);

ALTER TABLE USUARIOS ADD CONSTRAINT USUARIOS_LIVROS_PK PRIMARY KEY(ID);


CREATE SEQUENCE LIVROS_LIVROS_SEQ INCREMENT BY 1 START WITH 1;

CREATE TABLE LIVROS(
    ID      INT,
    TITULO  VARCHAR2(100),
    AUTOR   VARCHAR2(100),
    ISBN    VARCHAR2(50),
    PAGINAS INT,
    EDICAO  INT
);

ALTER TABLE LIVROS ADD CONSTRAINT LIVROS_LIVROS_PK PRIMARY KEY(ID);

CREATE SEQUENCE EMPRESTIMO_LIVROS_SEQ INCREMENT BY 1 START WITH 1;

CREATE TABLE EMPRESTIMOS(
    ID            INT,
    ID_USUARIO    INT,
    ID_LIVRO      INT,
    DT_EMP        DATE,
    DT_DEVOL      DATE
);

ALTER TABLE EMPRESTIMOS ADD CONSTRAINT EMPRESTIMOS_LIVROS_PK PRIMARY KEY(ID);
ALTER TABLE EMPRESTIMOS ADD CONSTRAINT EMPRESTIMOS_LIVROS_USUARIO_FK FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS;
ALTER TABLE EMPRESTIMOS ADD CONSTRAINT EMPRESTIMOS_LIVROS_LIVRO_FK FOREIGN KEY(ID_LIVRO) REFERENCES LIVROS;
